// Generates a synthetic set of products at any size, deterministically: a seeded generator and no clock or
// Math.random(), so the same count and seed give byte-identical output on any machine. It emits every
// projection an estate might load (a CMS create-request per product, the CMDB stub's view, COMPASS rows and
// SQL, and a manifest of what was planted); this repository uses the CMS projection, through
// regenerate-scale.mjs beside this file. Do not run it by hand to refresh the committed file.
//
//   node generate-scale.mjs --count 250 --seed 1 --out <dir>/scale
//
// --defects and --negatives plant deliberate faults for a data-quality checker to find; the suite's fixture is
// generated with neither, so every product is clean.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};
const COUNT = parseInt(arg('count', '250'), 10);
const SEED = parseInt(arg('seed', '1'), 10);
const OUT = resolve(arg('out', 'seed/scenarios/scale'));

// mulberry32 — small, fast, and above all reproducible across machines and Node versions, which
// Math.random() is not.
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6D2B79F5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = rng(SEED);
const pick = (xs) => xs[Math.floor(rand() * xs.length)];

// A DELIBERATELY WIDE vocabulary. The point of the near-duplicate rule is to catch services whose
// names are confusably similar, so a generator drawing from a narrow word list would manufacture
// exactly the collisions the rule is meant to flag and the result would say nothing about the rule.
// Distinctness here is a property the fixture must have for the measurement to mean anything, and
// it is asserted below rather than assumed.
const DOMAIN = ['Pupil', 'School', 'Teacher', 'Governor', 'Curriculum', 'Admissions', 'Attendance',
  'Safeguarding', 'Funding', 'Apprenticeship', 'Childcare', 'SEND', 'Ofsted', 'Bursary', 'Transport',
  'Catering', 'Estates', 'Workforce', 'Assessment', 'Careers', 'Library', 'Nursery', 'Academy',
  'Exclusions', 'Timetable', 'Behaviour', 'Wellbeing', 'Literacy', 'Numeracy', 'Languages'];
const THING = ['Register', 'Portal', 'Tracker', 'Dashboard', 'Finder', 'Manager', 'Service', 'Hub',
  'Checker', 'Planner', 'Directory', 'Gateway', 'Console', 'Workbench', 'Ledger', 'Index',
  'Scheduler', 'Reconciler', 'Notifier', 'Archive'];
const QUALIFIER = ['National', 'Regional', 'Local', 'Central', 'Unified', 'Integrated', 'Digital',
  'Statutory', 'Strategic', 'Operational', 'Consolidated', 'Federated'];
const PHASES = ['Discovery', 'Alpha', 'Private Beta', 'Public Beta', 'Live'];

const esc = (s) => String(s).replace(/'/g, "''");
const guid = (n) => `00000000-0000-0000-0009-${String(n).padStart(12, '0')}`;

// Titles must be UNIQUE and mutually distinct. Generated by exhausting combinations rather than
// sampling with replacement, because sampling would collide and the collisions would be
// indistinguishable from the thing being measured.
const titles = [];
const seen = new Set();
let guard = 0;
while (titles.length < COUNT && guard++ < COUNT * 200) {
  const t = `${pick(QUALIFIER)} ${pick(DOMAIN)} ${pick(THING)}`;
  if (seen.has(t)) continue;
  seen.add(t);
  titles.push(t);
}
if (titles.length < COUNT) {
  console.error(`FAILED: could only generate ${titles.length} distinct titles for --count ${COUNT}.`);
  console.error('The vocabulary is too small for this size — widen DOMAIN/THING/QUALIFIER rather');
  console.error('than allowing duplicates, which would corrupt the measurement this file exists for.');
  process.exit(1);
}

const products = titles.map((title, i) => {
  const n = i + 1;
  const url = `https://example.org/${title.toLowerCase().replace(/\s+/g, '-')}`;
  return {
    n,
    // ONE value, used as both COMPASS's CMDBID and the CMDB's sys_id, because that is what makes
    // them join. An earlier version generated two different strings — `SCALE-0001` on one side,
    // `scalesys000…001` on the other — and every single product came back uncorrelated: 250
    // R1-coverage findings, which reads as a totally unsynced estate rather than a fixture whose
    // two halves were never talking. The certified world does the same thing (`SEED-0001` on both
    // sides); the generator simply did not copy it.
    cmdbId: `SCALE-${String(n).padStart(4, '0')}`,
    get sysId() { return this.cmdbId; },
    guid: guid(n),
    title,
    phase: pick(PHASES),
    // The URL is IN the description, matching how the certified world plants WD-11: R6 fires on a
    // URL visible in the upstream description against an empty COMPASS ProductURL. Without it the
    // url-missing defect class was planted where no rule looks — R6 reads o.description, not
    // u_product_url — and the class could never be rediscovered, which rule-level scoring hid.
    description: `${title}. Synthetic service generated for the scale fixture. See ${url}.`,
    url,
    // Status 1 = active throughout: a clean fixture has no lifecycle divergence to find.
    status: 1,
    defect: null,   // set below when --defects is used
    negative: null, // set below when --negatives is used
  };
});

// ---- DEFECT PLANTING -------------------------------------------------------------------------
// The clean fixture measures FALSE POSITIVES: against it the hunter should find nothing, so
// anything it reports is wrong. That says nothing about RECALL — whether it still finds what it
// should when there is more to look through. Recall needs defects at known positions, which is
// what this does.
//
// Each defect is planted by DIVERGING the two sides the generator already emits — COMPASS's row
// and the CMDB stub's record — so the hunter meets exactly the cross-system disagreement it is
// built to detect. The manifest records which product carries which, BEFORE the fixture is used,
// so recall is a comparison against a recorded answer rather than a judgement about output.
//
// One defect per product at most, and never on the same product twice: overlapping defects make a
// miss ambiguous — you cannot tell whether the rule failed or another rule masked it.
const DEFECT_COUNT = parseInt(arg('defects', '0'), 10);

// Each entry says how to break the CMDB side away from the COMPASS side, and which FINDING KEYS
// the hunter must emit — subject-level, all of them, in the `RULE|key` form checks/findings.json
// uses. The expected keys are the load-bearing part: a fixture that plants damage without naming
// the detector measures nothing, and naming only the RULE lets an unrelated part of the estate
// answer for the planted defect. That happened: the earlier "12 of 12" recall figure was scored
// rule-level, and two of its classes were being credited by the certified world, not the fixture —
// url-malformed's R11 fired on the world's two AISS rows (the fixture loads no AISS side at all),
// and cmdb-orphan's R1-orphan fired on the stranded world, while the planted orphan actually
// surfaces as R1-coverage. Subject-level keys make that impossible.
//
// A title defect planted in the CMDB leaves BOTH downstream systems disagreeing with it, so two
// keys from one cause is correct per-system reporting, not duplication (docs/scale-findings.md).
const DEFECTS = [
  {
    kind: 'title-typo',
    apply: (p) => { p.cmdbTitle = p.title.replace(/([a-z])([a-z])/, '$2$1'); },
    expectedKeys: (p) => [`R2-title-typo|compass:${p.sysId}`, `R2-title-typo|cms:${p.sysId}`],
    note: 'two adjacent letters transposed — within edit distance 3, so a suspected typo',
  },
  {
    kind: 'title-case',
    apply: (p) => { p.cmdbTitle = p.title.toUpperCase(); },
    expectedKeys: (p) => [`R2-title-case|compass:${p.sysId}`, `R2-title-case|cms:${p.sysId}`],
    note: 'same title, different case — normalises equal, so case drift rather than a typo',
  },
  {
    kind: 'title-drift',
    apply: (p) => { p.cmdbTitle = `Completely Different Service Name ${p.n}`; },
    expectedKeys: (p) => [`R2-title-drift|compass:${p.sysId}`, `R2-title-drift|cms:${p.sysId}`],
    note: 'unrelated titles — too far apart to be a typo',
  },
  // DIRECTION MATTERS, and getting it wrong is how these two were first planted. Both rules fire
  // when COMPASS is EMPTY and the CMDB has a value — not the reverse. Emptying the CMDB side
  // planted damage neither rule looks for, and the run reported them as missed recall when the
  // fixture was simply pointing the wrong way.
  //
  // The reverse direction — CMDB empty, COMPASS populated — is NOT detected by any rule. That is a
  // real asymmetry in the hunter, found by this mistake and worth more than the defect was:
  // an upstream record losing its description or URL passes silently.
  {
    kind: 'description-missing',
    apply: (p) => { p.compassDescription = ''; },
    expectedKeys: (p) => [`R3-description-missing|compass:${p.sysId}`],
    note: 'COMPASS carries no description for a product the CMDB describes',
  },
  {
    kind: 'url-missing',
    apply: (p) => { p.compassUrl = ''; },
    expectedKeys: (p) => [`R6-url-missing|compass:${p.sysId}`],
    note: 'COMPASS carries no product URL where the CMDB description advertises one',
  },
  // url-malformed is RETIRED, not moved: it planted `htp:/not a url` in the CMDB's u_product_url,
  // which NO rule reads — R11 checks AISS service URLs, and this fixture loads no AISS side. The
  // class scored as "detected" only because rule-level matching credited it with the certified
  // world's two R11 findings (aiss:Admissions Appeals Manager, aiss:SEND support gateway).
  // Residue, stated plainly: R11 is unexercised at scale until the fixture grows an AISS side.
  {
    kind: 'cmdb-orphan',
    apply: (p) => { p.omitFromCompass = true; },
    // R1-COVERAGE, not R1-orphan: the offering exists in the CMDB and is absent from COMPASS,
    // which is the coverage direction. R1-orphan is the reverse (downstream row claiming a
    // correlation the headwater lacks) and fires here only on estate stranded by the scenario
    // swap — crediting it to this defect is exactly the mis-scoring subject-level keys prevent.
    expectedKeys: (p) => [`R1-coverage|compass:${p.sysId}`],
    note: 'present in the CMDB and CMS, absent from COMPASS — never ingested',
  },
];

const planted = [];
if (DEFECT_COUNT > 0) {
  if (DEFECT_COUNT > products.length) {
    console.error(`--defects ${DEFECT_COUNT} exceeds --count ${products.length}: one defect per product at most.`);
    process.exit(1);
  }
  // Spread evenly rather than clustered at the start, so a rule that only ever sees the first few
  // rows is not accidentally exercised more than one that sees the last few.
  const stride = Math.floor(products.length / DEFECT_COUNT) || 1;
  for (let k = 0; k < DEFECT_COUNT; k++) {
    const p = products[(k * stride) % products.length];
    if (p.defect) continue;                      // never two on one product
    const d = DEFECTS[k % DEFECTS.length];
    d.apply(p);
    p.defect = d.kind;
    planted.push({ cmdbId: p.cmdbId, sysId: p.sysId, title: p.title, kind: d.kind, expectedKeys: d.expectedKeys(p), note: d.note });
  }
}

// ---- KNOWN NEGATIVES -------------------------------------------------------------------------
// The other half of the measurement. Recall asks whether the planted defects are found; PRECISION
// asks whether anything innocent is flagged, and that needs innocents whose innocence is RECORDED,
// so a false positive appears as a disagreement with the manifest rather than as a judgement call.
//
// The clean remainder of this fixture is already a valid negative set — the generator emits both
// sides of every product from one array, so a non-defective product is innocent BY CONSTRUCTION,
// not by assumption. But those negatives are EASY: byte-identical pairs that no drift rule could
// flag under any plausible loosening, so precision measured only against them can never go red.
// These constructs are the tempting ones — each sits deliberately close to a rule's trigger while
// staying innocent by that rule's own documented intent — and they are what gives the number teeth.
//
// Constructs are planted from the TAIL of the product list; defects spread from the head, and a
// product carrying both would make any finding on it unattributable (same reason defects never
// double up). Retitled products stay unique — asserted, because a duplicate title would break the
// distinctness invariant the vocabulary section establishes.
const NEGATIVE_COUNT = parseInt(arg('negatives', '0'), 10);

const retitle = (p, title) => {
  if (p.defect) throw new Error(`negative construct would land on defect-carrying ${p.cmdbId}`);
  if (seen.has(title)) throw new Error(`negative title '${title}' collides with a generated one`);
  seen.delete(p.title);
  seen.add(title);
  p.title = title;
  p.url = `https://example.org/${title.toLowerCase().replace(/\s+/g, '-')}`;
  p.description = `${title}. Synthetic service generated for the scale fixture. See ${p.url}.`;
};

// Four-word titles throughout, deliberately outside the Qualifier-Domain-Thing space the generator
// samples, so a construct can never collide with a generated title whatever the seed.
const NEGATIVES = [
  {
    kind: 'near-title-pair', products: 2, tempts: 'R2/R13 typo rules, R9 near-duplicate',
    apply: (a, b) => { retitle(a, 'Regional Pupil Data Register'); retitle(b, 'National Pupil Data Register'); },
    note: 'edit distance 3 apart — the Regional/National naming pattern scale-findings.md predicted a ' +
      'real estate would carry. Two distinct services, fully correlated, identical on every system, ' +
      'so no cross-system rule has a difference to report; R9 fires only when a side has no id.',
  },
  {
    kind: 'near-title-pair-2', products: 2, tempts: 'R2/R13 typo rules, R9 near-duplicate',
    apply: (a, b) => { retitle(a, 'Statutory Bursary Reconciliation Ledger'); retitle(b, 'Statutory Nursery Reconciliation Ledger'); },
    note: 'edit distance 2 apart (Bursary/Nursery — a real confusable from the scale measurement), ' +
      'both fully correlated and consistent everywhere.',
  },
  {
    kind: 'shared-words-pair', products: 2, tempts: 'R9 near-duplicate',
    apply: (a, b) => { retitle(a, 'Integrated Attendance Insight Dashboard'); retitle(b, 'Integrated Attendance Insight Portal'); },
    note: 'three shared significant words — exactly R9\'s overlap threshold — but both products carry ' +
      'ids, and R9\'s finding is defined as "likely the same service, ONE UNMATCHABLE".',
  },
  {
    kind: 'case-style', products: 1, tempts: 'R2/R13/R8 case rules',
    apply: (a) => retitle(a, 'eVoucher SEND Payments Gateway'),
    note: 'unconventional but deliberate casing, identical on every system — case rules fire on ' +
      'cross-system DIFFERENCE, never on style.',
  },
  {
    kind: 'empty-description-both', products: 1, tempts: 'R3-description-missing',
    apply: (a) => {
      // COMPASS and CMDB both empty — consistently undescribed, which looks like the planted
      // description-missing defect but is not: R3 requires an upstream description to be missing
      // FROM. The CMS copy keeps text because the hunter never reads CMS descriptions and a
      // Strapi required-field refusal here would surface as a phantom coverage finding.
      a.description = ''; a.compassDescription = ''; a.cmdbDescription = '';
      a.cmsDescription = `${a.title}. Synthetic service generated for the scale fixture.`;
    },
    note: 'no description on either compared side — nothing upstream exists to be missing downstream',
  },
  {
    kind: 'unusual-url-consistent', products: 1, tempts: 'R6-url-missing, R11-url-malformed',
    apply: (a) => {
      const u = `https://example.org/services/${a.n}?view=full&ref=register`;
      a.url = u; a.compassUrl = u; a.cmdbUrl = u; a.cmsUrl = u;
      a.description = `${a.title}. Synthetic service generated for the scale fixture. See ${u}.`;
    },
    note: 'query-string URL, valid and identical everywhere — unusual-looking is not inconsistent',
  },
];

const knownNegatives = [];
if (NEGATIVE_COUNT > 0) {
  if (NEGATIVE_COUNT > NEGATIVES.length) {
    console.error(`--negatives ${NEGATIVE_COUNT} exceeds the ${NEGATIVES.length} defined constructs.`);
    process.exit(1);
  }
  let tail = products.length - 1;
  for (const neg of NEGATIVES.slice(0, NEGATIVE_COUNT)) {
    const targets = [];
    while (targets.length < neg.products && tail >= 0) {
      const p = products[tail--];
      if (!p.defect && !p.negative) targets.push(p);
    }
    if (targets.length < neg.products) { console.error(`ran out of clean products for negative '${neg.kind}'`); process.exit(1); }
    neg.apply(...targets);
    for (const p of targets) p.negative = neg.kind;
    knownNegatives.push({
      kind: neg.kind, tempts: neg.tempts,
      cmdbIds: targets.map(p => p.cmdbId), titles: targets.map(p => p.title),
      note: neg.note,
    });
  }
}

const sql = [
  `-- Scale fixture: ${COUNT} synthetic services, seed ${SEED}. GENERATED — do not hand-edit.`,
  `-- Regenerate: node seed/generate-scale.mjs --count ${COUNT} --seed ${SEED}`,
  '--',
  `-- Planted defects: ${DEFECT_COUNT}; known negatives: ${knownNegatives.length}. At the default of zero-zero`,
  '-- this fixture is DELIBERATELY CLEAN, so every finding against it is a false positive by',
  '-- construction. With --defects and --negatives it measures recall AND precision in one run:',
  '-- the manifest records which product carries which, so the two are separable per finding rather',
  '-- than mixed — an earlier version believed they needed separate runs, which was only true while',
  '-- the answer was recorded per run instead of per product.',
  '-- Loads on top of compass-minimal for its shared personas, lookups and roles.',
  '-- Idempotent: natural-key guarded on CMDBID like every other scenario here.',
  '',
  // A product marked omitFromCompass is deliberately absent from this side — that IS its defect.
  ...products.filter(p => !p.omitFromCompass).map(p =>
    `IF NOT EXISTS (SELECT 1 FROM CMDBProducts WHERE CMDBID = '${p.cmdbId}')\n` +
    `  INSERT INTO CMDBProducts (Id, Title, CMDBDescription, CMDBID, Status, PhaseId, IsEnterpriseService, IsMultiDepartmentProduct, ProductURL, CreatedAt, UpdatedAt)\n` +
    // `??` not `||`: an empty string is the planted defect for the missing-description and
    // missing-url cases, and `||` would quietly restore the value the defect removed.
    `  SELECT '${p.guid}', '${esc(p.title)}', N'${esc(p.compassDescription ?? p.description)}', '${p.cmdbId}', ${p.status}, ph.Id, 0, 0, '${esc(p.compassUrl ?? p.url)}', SYSUTCDATETIME(), SYSUTCDATETIME() FROM PhaseLookups ph WHERE ph.Name = '${p.phase}';`),
  '',
].join('\n');

// The CMDB stub's view. Identical values on purpose — a difference here would be a planted defect,
// and this fixture has none.
const cmdb = {
  $comment: `Scale fixture, ${COUNT} services, seed ${SEED}. GENERATED — do not hand-edit. ` +
    'Values match the COMPASS side exactly; any divergence found against this is a false positive.',
  // The CMDB side takes the diverged values where a defect planted them, and the matching values
  // everywhere else. `??` rather than `||` throughout: an empty string IS the planted defect for
  // the missing-description and missing-url cases, and `||` would helpfully undo it.
  //
  // The KEY AND FIELD NAMES must match what the CMDB stub reads — `service_offerings`, and
  // `description` / `parent.name` rather than invented equivalents. An earlier version used a
  // generic `records` key and the stub answered every request with ZERO records. Nothing failed:
  // the file loaded, parsed and served nothing, and the hunter reported 278 orphans, which reads
  // as a catastrophic estate rather than a fixture that was never being served. The contract is
  // seed/scenarios/cmdb-world.json.
  service_offerings: products.map(p => ({
    sys_id: p.sysId,
    name: p.cmdbTitle ?? p.title,
    description: p.cmdbDescription ?? p.description,
    'parent.name': 'Scale Fixture',
    u_product_url: p.cmdbUrl ?? p.url,
    u_phase: p.cmdbPhase ?? p.phase,
    install_status: '1',
  })),
  // Deliberately empty: R10 checks contact references against this list, and no generated product
  // references a person. Inventing users would plant defects the manifest does not record.
  sys_users: [],
};

// The CMS side. The hunter reads THREE sources — COMPASS, the FIPS CMS (Strapi) and the CMDB stub
// — so a fixture supplying only two of them cannot exercise it at all. That gap was found by
// trying to run it: the fixture was complete on its own terms and useless for its purpose.
//
// Emitted as Strapi's own create-request shape, one object per product, so loading is a POST loop
// against /api/products rather than a translation step. Products carrying a cmdb-orphan defect are
// present here for the same reason they are present in the CMDB: their absence from COMPASS is
// what the defect IS.
const cms = {
  $comment: `Scale fixture, ${COUNT} products, seed ${SEED}. GENERATED — do not hand-edit. ` +
    'Load with a POST per entry to the FIPS CMS at /api/products (needs a write token). ' +
    'cmdb_sys_id is the correlation key the hunter joins on; fips_id is deliberately omitted so ' +
    'the CMS mints its own, which is what a real ingest produces.',
  products: products.map(p => ({
    data: {
      title: p.cmsTitle ?? p.title,
      cmdb_sys_id: p.sysId,
      short_description: p.cmsDescription ?? p.description,
      long_description: p.description,
      product_url: p.cmsUrl ?? p.url,
      parent_category: 'Scale Fixture',
      state: 'Active',
    },
  })),
};

const manifest = {
  $comment: planted.length
    ? 'The known answer, recorded BEFORE the fixture is used. Within the fixture the hunter should ' +
      'emit EXACTLY the expectedKeys below — a missing key is lost recall, and any other ' +
      'fixture-scoped finding is a false positive, including one that touches a knownNegative. ' +
      'Findings outside the fixture (world estate stranded by the scenario swap) are environment ' +
      'artefacts with no recorded truth here, and are reported unscored rather than counted either ' +
      'way. checks/hunt-precision.mjs is the scorer.'
    : 'The known answer, recorded BEFORE the fixture is used. No defects are planted, so the ' +
      'hunter should produce ZERO findings; any it does produce are false positives at this scale.',
  generatedWith: { count: COUNT, seed: SEED, defects: planted.length, negatives: knownNegatives.length, deterministic: true },
  distinctTitles: titles.length,
  // Keyed the way checks/findings.json reports — `RULE|key`, subject-level — so comparison is a
  // set operation rather than a reading exercise. ALL of a defect's expectedKeys must appear: a
  // CMDB-side title defect legitimately yields one finding per downstream system.
  expected: planted,
  // Innocents recorded as innocent, each sitting close to a named rule's trigger. A finding that
  // touches one of these ids or titles is a false positive BY THIS RECORD, not by argument.
  knownNegatives,
  products: products.map(p => ({ cmdbId: p.cmdbId, sysId: p.sysId, title: p.title, defect: p.defect, negative: p.negative })),
};

mkdirSync(dirname(OUT), { recursive: true });
// The same COMPASS rows as `.sql`, in a form the shape profiler can read. Without this, COMPASS is
// the one system in the triangle that cannot be profiled or key-matched at all: the CMDB and CMS
// sides emit JSON and COMPASS emitted only INSERT statements, so any cross-system comparison
// silently became a two-way one. Deriving both from the same array keeps them from drifting — the
// alternative, parsing the SQL back, would be reconstructing data from its own loader.
const compassRows = products.filter(p => !p.omitFromCompass).map(p => ({
  Id: p.guid, Title: p.title, CMDBDescription: p.compassDescription ?? p.description,
  CMDBID: p.cmdbId, Status: p.status, Phase: p.phase, ProductURL: p.compassUrl ?? p.url,
}));

writeFileSync(`${OUT}.sql`, sql);
writeFileSync(`${OUT}.compass.json`, JSON.stringify(compassRows, null, 1));
writeFileSync(`${OUT}.cmdb.json`, JSON.stringify(cmdb, null, 1));
writeFileSync(`${OUT}.cms.json`, JSON.stringify(cms, null, 1));
writeFileSync(`${OUT}.manifest.json`, JSON.stringify(manifest, null, 1));

console.log(`generated ${COUNT} services (seed ${SEED}, deterministic)`);
console.log(`  ${OUT}.sql            ${compassRows.length} COMPASS rows`);
console.log(`  ${OUT}.compass.json   ${compassRows.length} COMPASS rows, profileable`);
console.log(`  ${OUT}.cmdb.json      ${products.length} CMDB records`);
console.log(`  ${OUT}.cms.json       ${cms.products.length} CMS create-requests`);
console.log(`  ${OUT}.manifest.json  planted defects: ${planted.length}, known negatives: ${knownNegatives.length}`);
if (planted.length) {
  const byKind = planted.reduce((a, d) => (a[d.kind] = (a[d.kind] ?? 0) + 1, a), {});
  console.log(`  planted: ${Object.entries(byKind).map(([k, n]) => `${k}×${n}`).join(', ')}`);
}
if (knownNegatives.length)
  console.log(`  negatives: ${knownNegatives.map(n => `${n.kind}(${n.cmdbIds.join(',')})`).join(', ')}`);
