// <auto-generated> by extract-shapes.cs from COMPASS's API controllers; regenerate, do not edit. </auto-generated>
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Compass.FipsApi.Contracts.Generated;

public static class Routes
{
    // GET /api/v1/ServiceRegister/products  (ServiceRegisterController.GetProducts)  ->  ServiceRegisterGetProductsResponse
    // GET /api/v1/ServiceRegister/categorisation-items  (ServiceRegisterController.GetCategorisationItems)  ->  ServiceRegisterGetCategorisationItemsResponse
    // GET /api/v1/ServiceRegister/fips | GET /api/v1/ServiceRegister/fips/configuration  (ServiceRegisterController.GetFipsConfigurationBundle)  ->  ServiceRegisterGetFipsConfigurationBundleResponse
    // GET /api/v1/ServiceRegister/fips/channels  (ServiceRegisterController.GetFipsChannelsV1)  ->  ServiceRegisterGetFipsChannelsV1Response
    // GET /api/v1/ServiceRegister/fips/types  (ServiceRegisterController.GetFipsTypesV1)  ->  ServiceRegisterGetFipsChannelsV1Response
    // GET /api/v1/ServiceRegister/fips/business-areas  (ServiceRegisterController.GetFipsBusinessAreasV1)  ->  ServiceRegisterGetFipsBusinessAreasV1Response
    // GET /api/v1/ServiceRegister/fips/user-groups  (ServiceRegisterController.GetFipsUserGroupsV1)  ->  ServiceRegisterGetFipsUserGroupsV1Response
    // GET /api/v1/ServiceRegister/fips/contact-roles  (ServiceRegisterController.GetFipsContactRolesV1)  ->  ServiceRegisterGetFipsContactRolesV1Response
    // GET /api/v1/ServiceRegister/fips/categorisation  (ServiceRegisterController.GetFipsCategorisationNestedV1)  ->  ServiceRegisterGetFipsCategorisationNestedV1Response
    // GET /api/v1/ServiceRegister/products/enterprise-active  (ServiceRegisterController.GetEnterpriseActiveProducts)  ->  ServiceRegisterGetProductsResponse
    // GET /api/v1/ServiceRegister/products/{id:guid}  (ServiceRegisterController.GetProduct)  ->  ServiceRegisterGetProductResponse
    // PATCH /api/v1/ServiceRegister/products/{id:guid}  (ServiceRegisterController.PatchProduct)  ->  ServiceRegisterPatchProductResponse
}

/// <summary>Built by GET /api/v1/ServiceRegister/products (ServiceRegisterController.GetProducts); GET /api/v1/ServiceRegister/products/enterprise-active (ServiceRegisterController.GetEnterpriseActiveProducts); GET /api/v1/ServiceRegister/products/{id:guid} (ServiceRegisterController.GetProduct).</summary>
public sealed class ServiceRegisterGetProductsResponseDataItemChannel : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/products (ServiceRegisterController.GetProducts); GET /api/v1/ServiceRegister/products/enterprise-active (ServiceRegisterController.GetEnterpriseActiveProducts); GET /api/v1/ServiceRegister/products/{id:guid} (ServiceRegisterController.GetProduct).</summary>
public sealed class ServiceRegisterGetProductsResponseDataItemCategory : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("groupId")] public int? GroupId { get; set; }
    [JsonPropertyName("groupName")] public string? GroupName { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/products (ServiceRegisterController.GetProducts); GET /api/v1/ServiceRegister/products/enterprise-active (ServiceRegisterController.GetEnterpriseActiveProducts); GET /api/v1/ServiceRegister/products/{id:guid} (ServiceRegisterController.GetProduct).</summary>
public sealed class ServiceRegisterGetProductsResponseDataItemContact : IContractRecord
{
    [JsonPropertyName("role")] public string? Role { get; set; }
    [JsonPropertyName("roleId")] public int? RoleId { get; set; }
    [JsonPropertyName("email")] public string? Email { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("canManage")] public bool? CanManage { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/products (ServiceRegisterController.GetProducts); GET /api/v1/ServiceRegister/products/enterprise-active (ServiceRegisterController.GetEnterpriseActiveProducts); GET /api/v1/ServiceRegister/products/{id:guid} (ServiceRegisterController.GetProduct).</summary>
public sealed class ServiceRegisterGetProductsResponseDataItem : IContractRecord
{
    [JsonPropertyName("id")] public Guid? Id { get; set; }
    [JsonPropertyName("uniqueId")] public int? UniqueId { get; set; }
    [JsonPropertyName("lastUpdated")] public DateTime? LastUpdated { get; set; }
    [JsonPropertyName("productName")] public string? ProductName { get; set; }
    [JsonPropertyName("phase")] public string? Phase { get; set; }
    [JsonPropertyName("businessArea")] public string? BusinessArea { get; set; }
    [JsonPropertyName("productUrl")] public string? ProductUrl { get; set; }
    [JsonPropertyName("status")] public string? Status { get; set; }
    [JsonPropertyName("isEnterpriseService")] public bool? IsEnterpriseService { get; set; }
    [JsonPropertyName("longDescription")] public string? LongDescription { get; set; }
    [JsonPropertyName("channels")] public List<ServiceRegisterGetProductsResponseDataItemChannel>? Channels { get; set; }
    [JsonPropertyName("types")] public List<ServiceRegisterGetProductsResponseDataItemChannel>? Types { get; set; }
    [JsonPropertyName("categories")] public List<ServiceRegisterGetProductsResponseDataItemCategory>? Categories { get; set; }
    [JsonPropertyName("contacts")] public List<ServiceRegisterGetProductsResponseDataItemContact>? Contacts { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/products (ServiceRegisterController.GetProducts); GET /api/v1/ServiceRegister/products/enterprise-active (ServiceRegisterController.GetEnterpriseActiveProducts).</summary>
public sealed class ServiceRegisterGetProductsResponsePagination : IContractRecord
{
    [JsonPropertyName("currentPage")] public int? CurrentPage { get; set; }
    [JsonPropertyName("pageSize")] public int? PageSize { get; set; }
    [JsonPropertyName("totalPages")] public int? TotalPages { get; set; }
    [JsonPropertyName("totalRecords")] public int? TotalRecords { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/products (ServiceRegisterController.GetProducts); GET /api/v1/ServiceRegister/products/enterprise-active (ServiceRegisterController.GetEnterpriseActiveProducts).</summary>
public sealed class ServiceRegisterGetProductsResponse : IContractRecord
{
    [JsonPropertyName("data")] public List<ServiceRegisterGetProductsResponseDataItem>? Data { get; set; }
    [JsonPropertyName("pagination")] public ServiceRegisterGetProductsResponsePagination? Pagination { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/categorisation-items (ServiceRegisterController.GetCategorisationItems).</summary>
public sealed class ServiceRegisterGetCategorisationItemsResponseDataItem : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("description")] public string? Description { get; set; }
    [JsonPropertyName("groupId")] public int? GroupId { get; set; }
    [JsonPropertyName("groupName")] public string? GroupName { get; set; }
    [JsonPropertyName("groupDescription")] public string? GroupDescription { get; set; }
    [JsonPropertyName("displayOrder")] public int? DisplayOrder { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/categorisation-items (ServiceRegisterController.GetCategorisationItems).</summary>
public sealed class ServiceRegisterGetCategorisationItemsResponse : IContractRecord
{
    [JsonPropertyName("data")] public List<ServiceRegisterGetCategorisationItemsResponseDataItem>? Data { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips | GET /api/v1/ServiceRegister/fips/configuration (ServiceRegisterController.GetFipsConfigurationBundle); GET /api/v1/ServiceRegister/fips/channels (ServiceRegisterController.GetFipsChannelsV1); GET /api/v1/ServiceRegister/fips/types (ServiceRegisterController.GetFipsTypesV1).</summary>
public sealed class ServiceRegisterGetFipsConfigurationBundleResponseChannel : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("description")] public string? Description { get; set; }
    [JsonPropertyName("displayOrder")] public int? DisplayOrder { get; set; }
    [JsonPropertyName("active")] public bool? Active { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips | GET /api/v1/ServiceRegister/fips/configuration (ServiceRegisterController.GetFipsConfigurationBundle); GET /api/v1/ServiceRegister/fips/business-areas (ServiceRegisterController.GetFipsBusinessAreasV1).</summary>
public sealed class ServiceRegisterGetFipsConfigurationBundleResponseBusinessArea : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("businessAreaLookupId")] public int? BusinessAreaLookupId { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("description")] public string? Description { get; set; }
    [JsonPropertyName("displayOrder")] public int? DisplayOrder { get; set; }
    [JsonPropertyName("active")] public bool? Active { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips | GET /api/v1/ServiceRegister/fips/configuration (ServiceRegisterController.GetFipsConfigurationBundle); GET /api/v1/ServiceRegister/fips/user-groups (ServiceRegisterController.GetFipsUserGroupsV1).</summary>
public sealed class ServiceRegisterGetFipsConfigurationBundleResponseUserGroup : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("description")] public string? Description { get; set; }
    [JsonPropertyName("displayOrder")] public int? DisplayOrder { get; set; }
    [JsonPropertyName("active")] public bool? Active { get; set; }
    [JsonPropertyName("children")] public List<string>? Children { get; set; }
    [JsonPropertyName("synonyms")] public List<string>? Synonyms { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips | GET /api/v1/ServiceRegister/fips/configuration (ServiceRegisterController.GetFipsConfigurationBundle); GET /api/v1/ServiceRegister/fips/contact-roles (ServiceRegisterController.GetFipsContactRolesV1).</summary>
public sealed class ServiceRegisterGetFipsConfigurationBundleResponseContactRole : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("description")] public string? Description { get; set; }
    [JsonPropertyName("allowMultiple")] public bool? AllowMultiple { get; set; }
    [JsonPropertyName("displayOrder")] public int? DisplayOrder { get; set; }
    [JsonPropertyName("active")] public bool? Active { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips | GET /api/v1/ServiceRegister/fips/configuration (ServiceRegisterController.GetFipsConfigurationBundle); GET /api/v1/ServiceRegister/fips/categorisation (ServiceRegisterController.GetFipsCategorisationNestedV1).</summary>
public sealed class ServiceRegisterGetFipsConfigurationBundleResponseCategorisationGroupItem : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("description")] public string? Description { get; set; }
    [JsonPropertyName("displayOrder")] public int? DisplayOrder { get; set; }
    [JsonPropertyName("active")] public bool? Active { get; set; }
    [JsonPropertyName("categorisationGroupId")] public int? CategorisationGroupId { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips | GET /api/v1/ServiceRegister/fips/configuration (ServiceRegisterController.GetFipsConfigurationBundle); GET /api/v1/ServiceRegister/fips/categorisation (ServiceRegisterController.GetFipsCategorisationNestedV1).</summary>
public sealed class ServiceRegisterGetFipsConfigurationBundleResponseCategorisationGroup : IContractRecord
{
    [JsonPropertyName("id")] public int? Id { get; set; }
    [JsonPropertyName("name")] public string? Name { get; set; }
    [JsonPropertyName("description")] public string? Description { get; set; }
    [JsonPropertyName("displayOrder")] public int? DisplayOrder { get; set; }
    [JsonPropertyName("active")] public bool? Active { get; set; }
    [JsonPropertyName("items")] public List<ServiceRegisterGetFipsConfigurationBundleResponseCategorisationGroupItem>? Items { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips | GET /api/v1/ServiceRegister/fips/configuration (ServiceRegisterController.GetFipsConfigurationBundle).</summary>
public sealed class ServiceRegisterGetFipsConfigurationBundleResponse : IContractRecord
{
    [JsonPropertyName("channels")] public List<ServiceRegisterGetFipsConfigurationBundleResponseChannel>? Channels { get; set; }
    [JsonPropertyName("types")] public List<ServiceRegisterGetFipsConfigurationBundleResponseChannel>? Types { get; set; }
    [JsonPropertyName("businessAreas")] public List<ServiceRegisterGetFipsConfigurationBundleResponseBusinessArea>? BusinessAreas { get; set; }
    [JsonPropertyName("userGroups")] public List<ServiceRegisterGetFipsConfigurationBundleResponseUserGroup>? UserGroups { get; set; }
    [JsonPropertyName("contactRoles")] public List<ServiceRegisterGetFipsConfigurationBundleResponseContactRole>? ContactRoles { get; set; }
    [JsonPropertyName("categorisationGroups")] public List<ServiceRegisterGetFipsConfigurationBundleResponseCategorisationGroup>? CategorisationGroups { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips/channels (ServiceRegisterController.GetFipsChannelsV1); GET /api/v1/ServiceRegister/fips/types (ServiceRegisterController.GetFipsTypesV1).</summary>
public sealed class ServiceRegisterGetFipsChannelsV1Response : IContractRecord
{
    [JsonPropertyName("data")] public List<ServiceRegisterGetFipsConfigurationBundleResponseChannel>? Data { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips/business-areas (ServiceRegisterController.GetFipsBusinessAreasV1).</summary>
public sealed class ServiceRegisterGetFipsBusinessAreasV1Response : IContractRecord
{
    [JsonPropertyName("data")] public List<ServiceRegisterGetFipsConfigurationBundleResponseBusinessArea>? Data { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips/user-groups (ServiceRegisterController.GetFipsUserGroupsV1).</summary>
public sealed class ServiceRegisterGetFipsUserGroupsV1Response : IContractRecord
{
    [JsonPropertyName("data")] public List<ServiceRegisterGetFipsConfigurationBundleResponseUserGroup>? Data { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips/contact-roles (ServiceRegisterController.GetFipsContactRolesV1).</summary>
public sealed class ServiceRegisterGetFipsContactRolesV1Response : IContractRecord
{
    [JsonPropertyName("data")] public List<ServiceRegisterGetFipsConfigurationBundleResponseContactRole>? Data { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/fips/categorisation (ServiceRegisterController.GetFipsCategorisationNestedV1).</summary>
public sealed class ServiceRegisterGetFipsCategorisationNestedV1Response : IContractRecord
{
    [JsonPropertyName("data")] public List<ServiceRegisterGetFipsConfigurationBundleResponseCategorisationGroup>? Data { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by GET /api/v1/ServiceRegister/products/{id:guid} (ServiceRegisterController.GetProduct).</summary>
public sealed class ServiceRegisterGetProductResponse : IContractRecord
{
    [JsonPropertyName("data")] public ServiceRegisterGetProductsResponseDataItem? Data { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by PATCH /api/v1/ServiceRegister/products/{id:guid} (ServiceRegisterController.PatchProduct).</summary>
public sealed class ServiceRegisterPatchProductResponseData : IContractRecord
{
    [JsonPropertyName("id")] public Guid? Id { get; set; }
    [JsonPropertyName("productUrl")] public string? ProductUrl { get; set; }
    [JsonPropertyName("message")] public string? Message { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}

/// <summary>Built by PATCH /api/v1/ServiceRegister/products/{id:guid} (ServiceRegisterController.PatchProduct).</summary>
public sealed class ServiceRegisterPatchProductResponse : IContractRecord
{
    [JsonPropertyName("data")] public ServiceRegisterPatchProductResponseData? Data { get; set; }

    [JsonExtensionData] public IDictionary<string, JsonElement>? Unexpected { get; set; }
}
